mod injection;
mod manifest;
mod manager;
mod marketplace;
mod remote;
mod render;
mod startup_sync;
mod store;

pub use manifest::PluginManifestInterface;
pub use manifest::PluginManifestPaths;
pub(crate) use manifest::load_plugin_manifest;
pub use manager::AppConnectorId;
pub use manager::ConfiguredMarketplace;
pub use manager::ConfiguredMarketplacePlugin;
pub(crate) use manager::PluginCapabilitySummary;
pub use manager::PluginDetail;
pub use manager::PluginInstallError;
pub use manager::PluginInstallOutcome;
pub use manager::PluginInstallRequest;
pub use manager::PluginReadOutcome;
pub use manager::PluginReadRequest;
pub use manager::PluginRemoteSyncError;
pub use manager::PluginUninstallError;
pub use manager::RemotePluginSyncResult;
pub use manager::PluginsManager;
pub use manager::load_plugin_apps;
pub use manager::OPENAI_CURATED_MARKETPLACE_NAME;
pub(crate) use injection::build_plugin_injections;
pub use marketplace::Marketplace;
pub use marketplace::MarketplaceError;
pub use marketplace::MarketplaceInterface;
pub use marketplace::MarketplacePluginAuthPolicy;
pub use marketplace::MarketplacePluginInstallPolicy;
pub use marketplace::MarketplacePluginPolicy;
pub use marketplace::MarketplacePluginSource;
pub use marketplace::MarketplacePlugin;
pub use marketplace::ResolvedMarketplacePlugin;
pub use marketplace::list_marketplaces;
pub use marketplace::resolve_marketplace_plugin;
pub use store::PluginId;
pub use store::PluginIdError;
pub use store::PluginInstallResult;
pub use store::PluginStore;
pub use store::PluginStoreError;
