#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SettingsSection {
    Model,
    Theme,
    Interface,
    Shell,
    ShellProfiles,
    ExecLimits,
    Updates,
    Accounts,
    Apps,
    Agents,
    Memories,
    Prompts,
    Skills,
    Plugins,
    AutoDrive,
    Review,
    Planning,
    Validation,
    Limits,
    Chrome,
    Mcp,
    JsRepl,
    Network,
    Notifications,
}

impl SettingsSection {
    #[cfg(not(target_os = "android"))]
    pub(crate) const ALL: [SettingsSection; 24] = [
        SettingsSection::Model,
        SettingsSection::Theme,
        SettingsSection::Interface,
        SettingsSection::Shell,
        SettingsSection::ShellProfiles,
        SettingsSection::ExecLimits,
        SettingsSection::Updates,
        SettingsSection::Accounts,
        SettingsSection::Apps,
        SettingsSection::Agents,
        SettingsSection::Memories,
        SettingsSection::Prompts,
        SettingsSection::Skills,
        SettingsSection::Plugins,
        SettingsSection::AutoDrive,
        SettingsSection::Review,
        SettingsSection::Planning,
        SettingsSection::Validation,
        SettingsSection::Chrome,
        SettingsSection::Mcp,
        SettingsSection::JsRepl,
        SettingsSection::Network,
        SettingsSection::Notifications,
        SettingsSection::Limits,
    ];

    #[cfg(target_os = "android")]
    pub(crate) const ALL: [SettingsSection; 23] = [
        SettingsSection::Model,
        SettingsSection::Theme,
        SettingsSection::Interface,
        SettingsSection::Shell,
        SettingsSection::ShellProfiles,
        SettingsSection::ExecLimits,
        SettingsSection::Updates,
        SettingsSection::Accounts,
        SettingsSection::Apps,
        SettingsSection::Agents,
        SettingsSection::Memories,
        SettingsSection::Prompts,
        SettingsSection::Skills,
        SettingsSection::Plugins,
        SettingsSection::AutoDrive,
        SettingsSection::Review,
        SettingsSection::Planning,
        SettingsSection::Validation,
        SettingsSection::Mcp,
        SettingsSection::JsRepl,
        SettingsSection::Network,
        SettingsSection::Notifications,
        SettingsSection::Limits,
    ];
}
