// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestPermissionProfile } from "../RequestPermissionProfile";
import type { PermissionGrantScope } from "./PermissionGrantScope";

export type PermissionsRequestApprovalResponse = { permissions: RequestPermissionProfile, scope: PermissionGrantScope, };
