// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRealtimeAudioChunk = { 
/**
 * Base64-encoded PCM audio.
 */
data: string, 
/**
 * Sample rate in Hz.
 */
sampleRate: number, 
/**
 * Number of channels.
 */
numChannels: number, 
/**
 * Number of samples per channel.
 */
samplesPerChannel: number | null, 
/**
 * Optional id of the item this audio belongs to.
 */
itemId: string | null, };
